name: CI

on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "backend/**"
      - ".github/workflows/**"

concurrency:  
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SUPABASE_JWT_SECRET: ${{ secrets.SUPABASE_JWT_SECRET }}
      # pip 최적화: 버전 체크 건너뛰기
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      # Python 최적화: 바이트코드 파일 생성 안 함
      PYTHONDONTWRITEBYTECODE: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: backend/requirements.txt

      - name: Install dependencies
        working-directory: backend
        run: pip install -r requirements.txt

      - name: Run tests
        working-directory: backend
        run: pytest -q
